name: "Laravel Pint"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  phpcs:
    name: "Running Laravel Pint check"
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, intl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test
